# The default language
language: en-US

# Whether to use the corresponding language that player uses
detect-player-locale: true

# Update check
check-update: true

# Mine settings
mine:
  # Allow place blocks in mines
  allow-place: false
  # Allow to players earn XP from skill plugins in mines
  # Note: support mcMMO and AuraSkills
  allow-earn-xp: true
  # Auto pickup settings
  auto-pickup:
    # Whether to enable auto pickup
    # You can use "/mine auto-pickup toggle" to toggle the state
    enabled: false
    # Enabled mines
    # Leave empty to use in all mines
    mines: []
    # Player who has this permission can use the feature
    # Set to empty to let all players can use
    permission: ""
    # Whether to enable the feature to the player automatically
    auto-enable: false

# Storage settings
# Require restart
storage:
  # Database type
  # Support: SQLite, MySQL, MariaDB, PostgreSQL
  type: sqlite
  remote:
    host: localhost
    port: 3306
    database: supermines
    username: root
    password: PASSWORD